logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true


server:
  tomcat:
    max-connections: 2000
    threads:
      max: 200
      min-spare: 10
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-http-form-post-size: -1
    connection-timeout: 5000
    keep-alive-timeout: 65000

#server.shutdown: graceful
#spring.lifecycle.timeout-per-shutdown-phase: 60s

spring:
  docker:
    compose:
      enabled: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    auto-commit: false
    connection-timeout: 3000
    max-lifetime: 50000
    pool-name: HikariCP-Writer
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/honmoon
    username: postgres
    password: postgres
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: never
