logging:
  level:
    root: info
    org.springframework.security: debug
    site.honmoon.auth: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    enable:
      all: false
  prometheus:
    metrics:
      export:
        enabled: false

server:
  tomcat:
    max-connections: 2000
    threads:
      max: 200
      min-spare: 10
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-http-form-post-size: -1
    connection-timeout: 5000
    keep-alive-timeout: 65000

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s

spring:
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: true
    locations: classpath:db/migration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.1
    gemini:
      api-key: ${GEMINI_API_KEY:}
      chat:
        completions-path: /v1beta/models/gemini-2.5-flash:generateContent
        base-url: https://generativelanguage.googleapis.com
        options:
          model: gemini-2.5-flash
          temperature: 0.1
  cloud:
    gcp:
      storage:
        project-id: ${GCP_PROJECT_ID:}
        bucket: ${GCP_BUCKET_NAME:}

  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 1000
          timeout: 4000
          writetimeout: 4000
          starttls:
            enable: true

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC
  datasource:
    auto-commit: false
    connection-timeout: 3000
    max-lifetime: 50000
    pool-name: HikariCP-Writer
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: never
management:
  health:
    mail:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/honmoon}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: never
management:
  health:
    mail:
      enabled: false
