### 회원가입 이메일 발송 (커스텀 callbackUrl)
POST {{host}}/api/auth/signup/email?callbackUrl=https://localhost:3000/auth/verify
Content-Type: application/json

{
  "email": "aekuya_@naver.com"
}

### 로그인 (이메일 + 비밀번호)
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "aekuya_@naver.com",
  "password": "mypassword123"
}

### 토큰 검증 (회원가입 완료)
POST {{host}}/api/auth/verify
Content-Type: application/json

{
  "token": "abHeknjYibUsS5TMuUNHvVxXwsFyRSlHP2QCuJmH8lE",
  "nickname": "지원",
  "password": "mypassword123"
}

### 실제 이메일 테스트 (회원가입) - 기본 URL
POST {{host}}/api/auth/signup/email
Content-Type: application/json

{
  "email": "aekuya_@naver.com"
}

### 내 프로필(간략)
GET {{host}}/api/users/me/profile/summary
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5NzQ2YWM4ZS1iNzAzLTQ2NzMtYWI1NC00NmVhZmFmMjQyNDYiLCJlbWFpbCI6ImFla3V5YV9AbmF2ZXIuY29tIiwiaWF0IjoxNzU2MTQwNTU5LCJleHAiOjE3NTYyMjY5NTl9.Ca-xKHcrl73DrSD9J7qxhdcGrYBKNnmBEO8ALcQSAQfeYibjzE7vqOtDhYU49CLb

> {%
    client.test("내 프로필(간략) - 200", () => {
        client.assert(response.status === 200, "Status must be 200 OK");
    });
%}

### 내 프로필(상세)
GET {{host}}/api/users/me/profile/detail
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5NzQ2YWM4ZS1iNzAzLTQ2NzMtYWI1NC00NmVhZmFmMjQyNDYiLCJlbWFpbCI6ImFla3V5YV9AbmF2ZXIuY29tIiwiaWF0IjoxNzU2MTQwNTU5LCJleHAiOjE3NTYyMjY5NTl9.Ca-xKHcrl73DrSD9J7qxhdcGrYBKNnmBEO8ALcQSAQfeYibjzE7vqOtDhYU49CLb

> {%
    client.test("내 프로필(상세) - 200", () => {
        client.assert(response.status === 200, "Status must be 200 OK");
    });
%}
