### Select environment: local or dev (http-client.env.json)
### Basic ADMIN login test (jiwondev/jiwondev by default)
GET {{host}}/api/auth/me
Authorization: Basic {{basicAuthBase64}}
Accept: application/json

> {%
%}

### Get Google OAuth authorization URL (acts as signup if first time)
# @name getGoogleUrl
GET {{host}}/api/auth/google/url?scope=profile%20email%20openid&redirectAfter=/
Accept: application/json

> {%
const res = JSON.parse(response.body);
client.test('Got auth URL', function() {
  client.assert(res.success === true, 'success must be true');
  client.assert(!!res.data.authorizationUrl, 'authorizationUrl must exist');
});
client.global.set('oauthState', res.data.state);
client.global.set('authorizationUrl', res.data.authorizationUrl);
%}

### Manual step
### 1) Open {{authorizationUrl}} in browser, login/consent
### 2) After redirect, copy the `code` param. The `state` is already stored.

### Exchange code -> session token (fill the code below)
# @name oauthCallback
GET {{host}}/api/auth/google/callback?code={{oauthCode}}&state={{oauthState}}
Accept: application/json

> {%
const res = JSON.parse(response.body);
client.test('OAuth callback ok', function() {
  client.assert(res.success === true, 'success must be true');
  client.assert(!!res.data.appSessionToken, 'appSessionToken must exist');
});
client.global.set('appSessionToken', res.data.appSessionToken);
%}

### Me with Bearer session token
GET {{host}}/api/auth/me
Authorization: Bearer {{appSessionToken}}
Accept: application/json

### Protected sample - Mission places (Bearer)
GET {{host}}/api/mission-places
Authorization: Bearer {{appSessionToken}}
Accept: application/json

### Protected sample - Raffle products (Basic)
GET {{host}}/api/raffle-products
Authorization: Basic {{basicAuthBase64}}
Accept: application/json

### File upload URL (Bearer). Note: userId is required by API currently
POST {{host}}/api/v1/files/upload-url
Authorization: Bearer {{appSessionToken}}
Content-Type: application/x-www-form-urlencoded

fileName={{fileName}}&folder={{folder}}&contentType={{contentType}}&userId={{userId}}

> {%
// Defaults for convenience
if (!client.global.get('fileName')) client.global.set('fileName', 'test.png');
if (!client.global.get('folder')) client.global.set('folder', 'images');
if (!client.global.get('contentType')) client.global.set('contentType', 'image/png');
%}

### Logout (Bearer)
POST {{host}}/api/auth/logout
Authorization: Bearer {{appSessionToken}}
Accept: application/json 
