create table if not exists flyway_schema_history
(
    installed_rank integer                 not null
        constraint flyway_schema_history_pk
            primary key,
    version        varchar(50),
    description    varchar(200)            not null,
    type           varchar(20)             not null,
    script         varchar(1000)           not null,
    checksum       integer,
    installed_by   varchar(100)            not null,
    installed_on   timestamp default now() not null,
    execution_time integer                 not null,
    success        boolean                 not null
);

create index if not exists flyway_schema_history_s_idx
    on flyway_schema_history (success);

create table if not exists point_history
(
    id          bigint generated by default as identity
        primary key,
    user_id     uuid                                                            not null,
    points      integer                                                         not null,
    description varchar(255)                                                    not null,
    created_by  varchar(255)             default 'anonymous'::character varying not null,
    created_at  timestamp with time zone default now()                          not null,
    modified_by varchar(255)             default 'anonymous'::character varying not null,
    modified_at timestamp with time zone default now()                          not null
);

create table if not exists mission_place
(
    id           bigint generated by default as identity
        primary key,
    name         varchar(255)                                                    not null,
    description  text,
    created_by   varchar(255)             default 'anonymous'::character varying not null,
    created_at   timestamp with time zone default now()                          not null,
    modified_by  varchar(255)             default 'anonymous'::character varying not null,
    modified_at  timestamp with time zone default now()                          not null,
    location     text,
    image        varchar(255),
    latitude     double precision,
    longitude    double precision,
    location_vec vector(2)
);

create index if not exists idx_mission_place_location_vec_l2
    on mission_place using ivfflat (location_vec);

create index if not exists idx_mission_place_lat_lng
    on mission_place (latitude, longitude);

create table if not exists raffle_product
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255)                                                    not null,
    description text,
    image_url   varchar(255),
    created_by  varchar(255)             default 'anonymous'::character varying not null,
    created_at  timestamp with time zone default now()                          not null,
    modified_by varchar(255)             default 'anonymous'::character varying not null,
    modified_at timestamp with time zone default now()                          not null,
    point_cost  integer                  default 100                            not null
);

create table if not exists raffle_user_application
(
    id                bigint generated by default as identity
        primary key,
    user_id           uuid                                                            not null,
    raffle_product_id bigint                                                          not null,
    created_by        varchar(255)             default 'anonymous'::character varying not null,
    created_at        timestamp with time zone default now()                          not null,
    modified_by       varchar(255)             default 'anonymous'::character varying not null,
    modified_at       timestamp with time zone default now()                          not null,
    application_date  timestamp with time zone default now()                          not null
);

create table if not exists user_activity
(
    id                    bigint generated by default as identity
        primary key,
    user_id               uuid                                                            not null,
    place_id              bigint                                                          not null,
    mission_id            bigint,
    description           text,
    is_correct            boolean                  default false,
    is_completed          boolean                  default false                          not null,
    points_earned         integer                  default 0                              not null,
    text_answer           text,
    selected_choice_index integer,
    uploaded_image_url    varchar(255),
    created_by            varchar(255)             default 'anonymous'::character varying not null,
    created_at            timestamp with time zone default now()                          not null,
    modified_by           varchar(255)             default 'anonymous'::character varying not null,
    modified_at           timestamp with time zone default now()                          not null,
    constraint unique_user_place
        unique (user_id, place_id)
);

create table if not exists mission_detail
(
    id                       bigint generated by default as identity
        primary key,
    title                    varchar(255)                                                    not null,
    description              text,
    points                   integer                                                         not null,
    mission_type             varchar(255)                                                    not null,
    place_id                 bigint,
    question                 text,
    answer                   text,
    choices                  jsonb,
    answer_explanation       text,
    correct_image_url        varchar(255),
    image_upload_instruction text,
    created_by               varchar(255)             default 'anonymous'::character varying not null,
    created_at               timestamp with time zone default now()                          not null,
    modified_by              varchar(255)             default 'anonymous'::character varying not null,
    modified_at              timestamp with time zone default now()                          not null
);

create table if not exists file_metadata
(
    id            uuid                     default gen_random_uuid()           not null
        primary key,
    user_id       uuid                                                         not null,
    file_name     varchar(255)                                                 not null,
    original_name varchar(255)                                                 not null,
    file_url      varchar(500)                                                 not null,
    file_size     bigint,
    content_type  varchar(100),
    folder        varchar(255)             default 'images'::character varying not null,
    created_by    varchar(255)             default 'system'::character varying not null,
    modified_by   varchar(255)             default 'system'::character varying not null,
    created_at    timestamp with time zone default now()                       not null,
    modified_at   timestamp with time zone default now()                       not null,
    is_active     boolean                  default true                        not null
);

create index if not exists idx_file_metadata_user_id
    on file_metadata (user_id);

create index if not exists idx_file_metadata_file_name
    on file_metadata (file_name);

create index if not exists idx_file_metadata_is_active
    on file_metadata (is_active);

create unique index if not exists idx_file_metadata_unique_active_file
    on file_metadata (file_name)
    where (is_active = true);

create table if not exists users
(
    id                uuid                                                            not null
        primary key,
    email             varchar(255),
    nickname          varchar(255),
    total_points      integer                  default 0                              not null,
    total_activities  integer                  default 0                              not null,
    profile_image_url varchar(255),
    password_hash     varchar(255),
    created_by        varchar(255)             default 'anonymous'::character varying not null,
    created_at        timestamp with time zone default now()                          not null,
    modified_by       varchar(255)             default 'anonymous'::character varying not null,
    modified_at       timestamp with time zone default now()                          not null,
    is_active         boolean                  default true
);


create table if not exists app_session
(

    token      varchar(64)                            not null primary key,
    subject    varchar(255)                           not null,
    email      varchar(255),
    name       varchar(255),
    picture    varchar(500),
    provider   varchar(50)                            not null,
    expires_at timestamp with time zone               not null,
    created_at timestamp with time zone default now() not null
);

create index if not exists idx_app_session_expires_at on app_session (expires_at);

create table if not exists magic_link_token
(
    token      varchar(64)                            not null primary key,
    email      varchar(255)                           not null,
    expires_at timestamp with time zone               not null,
    created_at timestamp with time zone default now() not null
);

create index if not exists idx_magic_link_token_expires_at on magic_link_token (expires_at);

