-- 이메일 인증 토큰 테이블 생성
CREATE TABLE IF NOT EXISTS public.email_auth_tokens
(
    id            bigint generated by default as identity
        primary key,
    email         varchar(255)             NOT NULL,
    token         varchar(255)             NOT NULL UNIQUE,
    expires_at    timestamp with time zone NOT NULL,
    used          boolean                  NOT NULL DEFAULT false,
    created_by    VARCHAR(255)             NOT NULL DEFAULT 'anonymous',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    modified_by   VARCHAR(255)             NOT NULL DEFAULT 'anonymous',
    modified_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_email_auth_tokens_token ON public.email_auth_tokens (token);
CREATE INDEX IF NOT EXISTS idx_email_auth_tokens_email ON public.email_auth_tokens (email);
CREATE INDEX IF NOT EXISTS idx_email_auth_tokens_expires_at ON public.email_auth_tokens (expires_at);
